* File Explorer is is an alternative to ls, written in c++
I did this mostly for fun, practice and something to keep myself occupied with. It is very lacking and should not be used as a serious alternative to ls.

** Installation

1) Clone the repository: via https: =git clone https://github.com/Eurydice86/file_explorer.git= or ssh: =git clone git@github.com:Eurydice86/file_explorer.git=
2) Add the executable to your system PATH (for instance, you can copy it to =/usr/local/bin/=: =sudo cp file_explorer/fexp /usr/local/bin/=)
3) You can then remove the cloned repo: =rm -rf file_explorer=

** Usage
You can use the command =fexp= followed by the path to the directory whose contents you would like to display, similar to how you would use =ls=. If no path given, fexp will display the current directory's contents.

** Features
- Directory names are shown in a different colour.
- Files and directories also show an icon next to them.

** Known issues
+ This does not (yet) work with directory names like "~" or "/". In fact it only supports paths given relative to the current one.
+ It currently displays everything in the given path.
+ README.org is displayed as "%".

** To do
+ Fix bug mentioned in the first known issue.
+ Add more icons.
+ Implement filtering of the results.
